module.exports = [{
    metadata: {
        iso_language_code: 'en',
        result_type: 'recent'
    },
    created_at: 'Sun Feb 22 19:42:26 +0000 2015',
    id: 569583011634806800,
    id_str: '569583011634806785',
    text: '10/10 would watch 🙌 #Fiftyshades #Grumpycat http://t.co/fSpMrxIken',
    source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 2167276806,
        id_str: '2167276806',
        name: 'Eli Lorenzo',
        screen_name: 'Marshall_lee93',
        location: '',
        profile_location: null,
        description: 'Hi there! :p\nim 19\nGamer\ni like to watch movies (especially the Marvel movies lol),\nim a chill dude\ni like making new friends so feel free to talk to me. ^-^',
        url: null,
        entities: [Object],
        protected: false,
        followers_count: 97,
        friends_count: 754,
        listed_count: 0,
        created_at: 'Thu Oct 31 21:29:11 +0000 2013',
        favourites_count: 232,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 228,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/553367581080317952/FHNsjyPV_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/553367581080317952/FHNsjyPV_normal.jpeg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/2167276806/1422379221',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 6,
    favorite_count: 2,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [],
        urls: [Object]
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
}, {
    metadata: {
        iso_language_code: 'en',
        result_type: 'recent'
    },
    created_at: 'Sun Feb 22 19:41:07 +0000 2015',
    id: 569582677914984450,
    id_str: '569582677914984448',
    text: 'Oscars are here #oscarparty #dovreclub #grumpycat #oscars http://t.co/QEz0tfCq16',
    source: '<a href="http://www.apple.com" rel="nofollow">iOS</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 105892064,
        id_str: '105892064',
        name: 'Traci Ramos',
        screen_name: 'ramosity1',
        location: 'San Francisco',
        profile_location: null,
        description: 'Avid Reader,  #Traveler - http://t.co/jykfQKJzo6,  #Blogger - http://t.co/eKI8xoMpQL, Long term love affair with Wonder Woman and Pepsi,',
        url: 'http://t.co/KjTmqyb8a5',
        entities: [Object],
        protected: false,
        followers_count: 845,
        friends_count: 1454,
        listed_count: 14,
        created_at: 'Sun Jan 17 21:06:41 +0000 2010',
        favourites_count: 713,
        utc_offset: -28800,
        time_zone: 'Pacific Time (US & Canada)',
        geo_enabled: true,
        verified: false,
        statuses_count: 2488,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: '0099B9',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/378800000068687310/8844bdf2d3114878f371bd7568e2c776.jpeg',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/378800000068687310/8844bdf2d3114878f371bd7568e2c776.jpeg',
        profile_background_tile: true,
        profile_image_url: 'http://pbs.twimg.com/profile_images/557938233263149057/Jl4LGRRQ_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/557938233263149057/Jl4LGRRQ_normal.jpeg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/105892064/1421857847',
        profile_link_color: '0099B9',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: '95E8EC',
        profile_text_color: '3C3940',
        profile_use_background_image: true,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 5,
    favorite_count: 10,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [],
        urls: [],
        media: [Object]
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
}, {
    metadata: {
        iso_language_code: 'en',
        result_type: 'recent'
    },
    created_at: 'Sun Feb 22 19:31:57 +0000 2015',
    id: 569580372910071800,
    id_str: '569580372910071808',
    text: 'Oscars tonight!!! #Oscars2015 #AcademyAwards #awardseason #Hollywoodlife #TardarSauce #GrumpyCat… http://t.co/ROmxSaQYuh',
    source: '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 2502433612,
        id_str: '2502433612',
        name: 'Sabrina Shereen',
        screen_name: 'The_Style_Era',
        location: 'Philadelphia, PA ',
        profile_location: null,
        description: 'If you love fashion, follow me for daily retweets, pics, articles, & quotes that will keep you up - to - date with what\'s hot in fashion now! :)',
        url: null,
        entities: [Object],
        protected: false,
        followers_count: 242,
        friends_count: 1873,
        listed_count: 7,
        created_at: 'Tue Apr 22 19:09:47 +0000 2014',
        favourites_count: 147,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 680,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'C0DEED',
        profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/568651796915449856/h30s2OmU_normal.jpeg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/568651796915449856/h30s2OmU_normal.jpeg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/2502433612/1424412127',
        profile_link_color: '0084B4',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        default_profile: true,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweet_count: 20,
    favorite_count: 0,
    entities: {
        hashtags: [Object],
        symbols: [],
        user_mentions: [],
        urls: [Object]
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
}];